# Generated by Django 5.1.2 on 2024-10-19 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Customer's email address for order notifications",
                        max_length=255,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address"
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                            ("PREPARING", "Preparing"),
                            ("READY", "Ready"),
                        ],
                        default="CONFIRMED",
                        help_text="Order status (Confirmed, Rejected, Preparing, Ready)",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the order was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the order was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="orders_orde_status_25e057_idx",
                    )
                ],
            },
        ),
    ]
